Conditions:
  ShouldSetupMealsCDN: !And
  - !Not
    - !Equals
      - ${env:MEALS_CDN_DOMAIN_NAME, ''}
      - ''
  - !Not
    - !Equals
      - ${env:MEALS_CDN_CERTIFICATE_ARN, ''}
      - ''



Resources:
  MealBucketCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: !If
          - ShouldSetupMealsCDN
          -
            - ${env:MEALS_CDN_DOMAIN_NAME, ''}
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - ShouldSetupMealsCDN
          -
            AcmCertificateArn: ${env:MEALS_CDN_CERTIFICATE_ARN, ''}
            MinimumProtocolVersion: TLSv1.2_2025
            SslSupportMethod: sni-only
          -
            CloudFrontDefaultCertificate: true
        HttpVersion: http2and3
        ConnectionMode: direct
        Origins:
          - DomainName: !GetAtt MealsBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          ViewerProtocolPolicy: redirect-to-https

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ${self:service}-${sls:stage}-OriginAccessControl
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  MealBucketCDNPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MealsBucket
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Effect: Allow
            Principal:
               Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub ${MealsBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${MealBucketCDN}'

