Resources:
    UserPool:
      Type : AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognito.UserPoolName}
        MfaConfiguration: OFF
        DeletionProtection: INACTIVE
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          From: ${env:COGNITO_EMAIL}
          ReplyToEmailAddress: ${env:COGNITO_EMAIL_TO_REPLY}
          SourceArn: ${env:SES_SOURCE_ARN}
        Schema:
          - Name: internalId
            Mutable: false
            AttributeDataType: String
            Required: false
        LambdaConfig:
          PreTokenGenerationConfig:
            LambdaArn: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-preTokenGenerationTrigger'
            LambdaVersion: V2_0

    PreTokenGenerationLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt PreTokenGenerationTriggerLambdaFunction.Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt UserPool.Arn

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${sls:stage}-UserPoolClient
        UserPoolId: !Ref UserPool
        GenerateSecret: true
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
        AccessTokenValidity: 1
        RefreshTokenValidity: 7
        TokenValidityUnits:
          AccessToken: days
          RefreshToken: days
        RefreshTokenRotation:
          Feature: ENABLED
          RetryGracePeriodSeconds: 0
