statements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:UpdateItem
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub "${MainTable.Arn}/index/*"
  - Effect: Allow
    Action:
      - cognito-idp:AdminDeleteUser
      - cognito-idp:AdminUpdateUserAttributes
      - cognito-idp:ListUsers
      - cognito-idp:AdminCreateUser
      - cognito-idp:AdminLinkProviderForUser
    Resource: !GetAtt UserPool.Arn
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource:
      - !GetAtt MealsBucket.Arn
      - !Sub ${MealsBucket.Arn}/*
  - Effect: Allow
    Action:
      - sqs:SendMessage
    Resource: !GetAtt MealsQueue.Arn

